import { useState } from "react";
import { ArrowUpRight, Boxes, ClipboardList, Cloud, Headphones, Plus, ShieldCheck, Wallet } from "lucide-react";
import { LiveRevenue } from "./ControlCenter";

const money = (value, currency) => `${Number(value || 0).toLocaleString("fr-FR", { maximumFractionDigits: 2 })} ${currency || "USDT"}`;
export default function WorkspaceHome({ data, onNavigate }) {
  const [tab, setTab] = useState("priorities");
  const s = data.summary || {};
  const queues = [
    { page: "orders", icon: ClipboardList, title: "Commandes à traiter", count: s.pending_orders, text: "Contrôler les paiements et suivre les livraisons", tone: "amber" },
    { page: "support", icon: Headphones, title: "Demandes de support", count: s.open_tickets, text: "Retrouver les conversations en attente", tone: "blue" },
    { page: "inventory", icon: Boxes, title: "Stock à surveiller", count: s.low_stock_offers, text: "Réapprovisionner les offres sous le seuil", tone: "rose" },
  ];
  return <div className="workspace-home"><div className="workspace-intro"><div><span className="eyebrow">WORKSPACE / COMMERCE</span><h2>Tout commence ici<span>.</span></h2><p>Votre boutique, vos opérations, vos prochaines décisions.</p></div><button onClick={() => onNavigate("catalog")}><Plus size={18} />Gérer le catalogue</button></div>
    <section className="workspace-scoreboard" aria-label="Chiffres clés"><div><span>Revenus aujourd’hui</span><strong>{money(s.revenue_today, data.currency)}</strong><small>Commandes encaissées</small></div><div><span>Commandes du jour</span><strong>{s.orders_today ?? "—"}</strong><small>Activité de la boutique</small></div><div><span>Stock disponible</span><strong>{s.available_inventory ?? "—"}</strong><small>Unités dans l’inventaire</small></div><div><span>Nouveaux clients</span><strong>{s.new_users_today ?? "—"}</strong><small>Aujourd’hui</small></div></section>
    <div className="workspace-columns"><div className="workspace-main"><div className="workspace-tabs" role="group" aria-label="Vue de l’accueil"><button aria-pressed={tab === "priorities"} onClick={() => setTab("priorities")}>Mes priorités</button><button aria-pressed={tab === "performance"} onClick={() => setTab("performance")}>Performance</button><button aria-pressed={tab === "recent"} onClick={() => setTab("recent")}>Dernières commandes</button></div>
      {tab === "priorities" && <section className="workspace-inbox"><header><span>FILE DE TRAVAIL</span><small>Selon le dernier état synchronisé</small></header>{queues.map(({ page, icon: Icon, title, text, count, tone }) => <button key={page} onClick={() => onNavigate(page)}><span className={`workspace-task-icon ${tone}`}><Icon size={22} /></span><span className="workspace-task-copy"><strong>{title}</strong><small>{text}</small></span><b>{count ?? "—"}</b><ArrowUpRight size={20} /></button>)}<footer><ShieldCheck size={16} />Chaque intervention reste reliée à son outil de gestion.</footer></section>}
      {tab === "performance" && <LiveRevenue currency={data.currency} />}
      {tab === "recent" && <section className="workspace-inbox"><header><span>COMMANDES RÉCENTES</span><button onClick={() => onNavigate("orders")}>Tout consulter →</button></header>{(data.orders || []).slice(0, 6).map((order) => <button key={order.id} onClick={() => onNavigate("orders")}><span className="workspace-task-icon"><ClipboardList size={20} /></span><span className="workspace-task-copy"><strong>#{order.id} · {order.offer_name || "Commande"}</strong><small>{order.username ? `@${order.username}` : `Client ${order.user_id}`}</small></span><b>{money(order.charged_total ?? Number(order.total_price || 0) + Number(order.wallet_amount || 0), data.currency)}</b><ArrowUpRight size={18} /></button>)}{!data.orders?.length && <p className="control-empty">Aucune commande récente à afficher.</p>}</section>}
      <section className="workspace-launcher"><header><h3>Votre espace de travail</h3><p>Des outils organisés autour de vos opérations.</p></header><div>{[["catalog", Boxes, "Catalogue", "Offres, prix et disponibilités"], ["api-products", Cloud, "Fournisseurs", "Connexions et produits externes"], ["deposits", Wallet, "Finance", "Dépôts et vérifications"], ["data-explorer", ClipboardList, "Données", "Rechercher, filtrer, exporter"]].map(([page, Icon, title, text]) => <button key={page} onClick={() => onNavigate(page)}><Icon size={23} /><strong>{title}</strong><small>{text}</small><ArrowUpRight size={18} /></button>)}</div></section>
    </div><aside className="workspace-context"><div className="workspace-bot-card"><span>VOTRE BOUTIQUE</span><div className="workspace-orbit"><span>↗</span></div><h3>{data.shop_name || "Black Market"}</h3><p>@{data.bot_username || "—"}</p><button onClick={() => onNavigate("control-center")}>Ouvrir le centre de contrôle <ArrowUpRight size={16} /></button></div><section><span className="eyebrow">ACCÈS DIRECT</span><h3>Un espace, tous vos outils.</h3><p>Retrouvez les diagnostics, les préférences et les connexions dans Administration.</p><button onClick={() => onNavigate("settings")}>Paramètres de la boutique →</button></section></aside></div></div>;
}
